// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreValidator.Data;

namespace StoreValidator.Migrations
{
    [DbContext(typeof(StoreValidatorDbContext))]
    [Migration("20180723193527_DeptTest")]
    partial class DeptTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreValidator.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<bool>("Concessions");

                    b.Property<string>("Desc")
                        .HasMaxLength(120);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("OpenDate");

                    b.Property<string>("PostCode");

                    b.Property<long>("StoreSize");

                    b.Property<int>("StoreType");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("StoreValidator.Models.StoreDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepDescription");

                    b.Property<long>("DepSize");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("Name");

                    b.Property<int?>("StoreId");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreDepts");
                });

            modelBuilder.Entity("StoreValidator.Models.StoreDepartment", b =>
                {
                    b.HasOne("StoreValidator.Models.Store")
                        .WithMany("Departments")
                        .HasForeignKey("StoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
